### ISSUE TITLE
Missing String

### ISSUE THREAD

**Issue by asdfzz** [amazfitbip/tools#19]
Hi first thanks for awesome project!
You guys miss a string in italian translation ( alarm )
pict: https://s26.postimg.org/ia693txnt/IMG_20170912_131608.jpg

**Comment by dpeddi** [comment]
You used one of the file on this project to patch your fw file?

**Comment by asdfzz** [comment]
I used an already patched one..
Francko76 ita fw 0.0.8.74

**Comment by dpeddi** [comment]
Hi think Franko read about this, but this isn't an issue related to this project.
