### ISSUE TITLE
403 resources, just 20 extracted

### ISSUE THREAD

**Issue by francko76** [amazfitbip/tools#2]
with the latest res2img... (29th august)

![image](https://user-images.githubusercontent.com/20030608/29812520-2de330ec-8ca7-11e7-8ab5-9f7e666ed874.png)

**Comment by dpeddi** [comment]
I know... 
some work in progress I need to add some flags like on translator tool.

for now just comment out:
extract_list = list(strings_cn.keys())

the res id well known will be translated automatically and it will be generated a new image using the dict structure in the tool itself

**Comment by francko76** [comment]
I've translated .fw in italian via hex, but 0.8.74 has no weather strings, in fact weather doesn't works on bip with the latest version (known bug).
I would create png or bmp in italian, but I'm not sure about the width resolution, some are streched by half /2... aren't they ?

I follow you... ( telegram me @francko76 )
I'm doing tests

**Comment by dpeddi** [comment]
Most of the width are ok... Some no.. Im investigating as well

**Comment by dpeddi** [comment]
fixed (with you help ;-) )
