### ISSUE TITLE
Txt. file in Amazfit Bip

### ISSUE THREAD

**Issue by mellijr** [amazfitbip/tools#26]
Hi, it's possible someone say me how get txt. file to translate a new .fw?. I decompress Mi Fit.apk and I obtain .fw file but I don't know how get .txt file to translate, thanks and best regards.

**Comment by dpeddi** [comment]
the txt files are on this repository. Take one of them and start from it

**Comment by wojtekadams** [comment]
@dpeddidid you generate manually the zh-cn2en.txt.0.0.8.32 file?

**Comment by wojtekadams** [comment]
@dpeddi you generate manually the zh-cn2en.txt.0.0.8.32 file?

**Comment by tomurbanowicz** [comment]
@dpeddi  - how to generate from FW (stock) translated base file TXT?

**Comment by dpeddi** [comment]
Manually. I wouldn't do it automatically. Too many dangerous. Every string come from 0.0.8.20 and i've checked that each string was called from the function who display them. On later firmware the procedure was a little different but we already known the string.

Probably is possible to automate but you risk to replace false positive strings.

**Comment by mellijr** [comment]
Do you have 0.0.8.97? and it's possible you say me command "zh-merge_old2new_trans.py" for translate since my own .txt file I translated?, thanks.

**Comment by dpeddi** [comment]
tou can apply an old translation file and fix the warning on offset manually or you can put 000001 on all offset if you are brave

**Comment by mellijr** [comment]
But how do it, what is the command I use it?, thanks.
