### ISSUE TITLE
zh-cn2en.py and russian TXT

### ISSUE THREAD

**Issue by tomurbanowicz** [amazfitbip/tools#29]
Traceback (most recent call last):
  File "ru-fw.py", line 213, in <module>
    s="".join(s_ar)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x98 in position 0: invalid start byte

**Comment by dpeddi** [comment]
probably your input file is corrupted.

**Comment by tomurbanowicz** [comment]
OK,  but I have problem with russian letters in script. How to do that with russian?
Ex. 

00000001|41 47 50 53 E5 8D 87 E7 B4 9A E4 B8 AD|AGPS升級中|Обновление AGPS
00000001|41 47 50 53 E5 8D 87 E7 B4 9A E5 A4 B1 E6 95 97|AGPS升級失敗|Ошибка обновл. AGPS
00000001|41 47 50 53 E5 8D 87 E7 B4 9A E6 88 90 E5 8A 9F|AGPS升級成功|Обновл. AGPS ОК
00000001|41 47 50 53 E5 8D 87 E7 BA A7 E4 B8 AD|AGPS升级中|Обновление AGPS
00000001|41 47 50 53 E5 8D 87 E7 BA A7 E5 A4 B1 E8 B4 A5|AGPS升级失败|Ошибка обновл. AGPS
00000001|41 47 50 53 E5 8D 87 E7 BA A7 E6 88 90 E5 8A 9F|AGPS升级成功|Обновл. AGPS ОК
00000001|41 47 50 53 E5 90 8E E5 8F AF E5 8A A0 E5 BF AB E5 AE 9A E4 BD 8D|AGPS后可加快定位|AGPS улучшит местопол.
