### ISSUE TITLE
res2img and problem with change some pictures

### ISSUE THREAD

**Issue by tomurbanowicz** [amazfitbip/tools#36]
I try to change that files:

170.png
171.png
172.png
173.png
174.png
175.png
176.png
177.png
178.png
179.png

but no result on the watch

![podmiana](https://user-images.githubusercontent.com/31843138/30850690-9d265f3c-a2a6-11e7-804d-688e6f204427.jpg)

**Comment by heartlandzf** [comment]
that character is drawn by the firmware, you can't edit in resources.

170.png belongs to 'default watchface', the one you see in the advertising.
