### ISSUE TITLE
Error with res2img.py

### ISSUE THREAD

**Issue by tqqviet** [amazfitbip/tools#39]
I got this error when open res2img.py:
SyntaxError: invalid syntax (res2img.py, line 56)
Please help me.
![res2img py error](https://user-images.githubusercontent.com/32427730/31052290-cc63955a-a6aa-11e7-8a6b-88aad381bc3f.png)

**Comment by dpeddi** [comment]
RTFM: you have to use python 2.7+ (<3.x)
