### ISSUE TITLE
GPS not tracking

### ISSUE THREAD

**Issue by motemoment** [amazfitbip/tools#53]
I'm try firmware amazfit bip 0.10.0.87 En force. test with sport mode outdoor running. 
after push button and wait a long time for get GPS signal. (not happen 5 mins)

when I'm skip and start running around 10 mins 2-3 km. and stop it for save data.
But It's show message  too short distants for save. and no tracking to save
(outdoor very open area)
please help me to check this bug

**Comment by motemoment** [comment]
edit: version 0.1.0.87

**Comment by dpeddi** [comment]
This isn't an issue related to our work.
