### ISSUE TITLE
Combining character

### ISSUE THREAD

**Issue by BabyEqual** [amazfitbip/tools#55]
Could you make BIP combine character, cause some character is over/under previous character.
https://en.wikipedia.org/wiki/Combining_character

For example: 
ḱṷṓn (U+006B U+0301 U+0075 U+032D U+006F U+0304 U+0301 U+006E)
ḱ (U+006B U+0301)
ṷ (U+0075 U+032D)
ṓ (U+006F U+0304 U+0301)

Could you check it from name like 03012U.bmp  ("U" means upper) 
and 032D2L.bmp ("L" means lower) 

Thank max in advance.

**Comment by dpeddi** [comment]
impossible to do, since we have a binary firmware
