### ISSUE TITLE
How to add own translation?

### ISSUE THREAD

**Issue by Tymcio** [amazfitbip/tools#7]
I would like to add Polish, could you briefly explain how to do it? :)

**Comment by flippy12** [comment]
You can take a look at the readme, and at the files already created, to understand how it's organized.
For your translation, you can start by downloading an existing file (like "zh-cn2en.txt.0.0.8.74") to see how it's structured. You will see that each line is finished by chinese_text|translated_text.
translated_text is the result of your translation.
The result of your translation will give the file zh-cn2**po**.txt.0.0.8.74 (I suppose that it's 'po' for Poland).

**Comment by Tymcio** [comment]
So I just translate this file and than I can commit it here ? 
I believe cn2pl will be for Polish (usually it's like this)

**Comment by dpeddi** [comment]
fork the repository do the changes you think we need, then do a pull request

**Comment by Tymcio** [comment]
Ok, great :) Could you tell me how to compile .res and .fw file with Polish language now? :)

**Comment by Tymcio** [comment]
Ok, great :) @dpeddi could you tell me how to make new .res and new .fw file, with PL translation inside? :)

**Comment by dpeddi** [comment]
Res2img -u

Or

res2img -u -a

res2img -p

You can add -i param as well with thw name of the res file

Il 05 set 2017 6:25 PM, "Marcin" <notifications@github.com> ha scritto:

**Comment by Tymcio** [comment]
Ok, will try ;)

**Comment by Tymcio** [comment]
Hmm, I have problem like this (https://scr.hu/GZOmRz) when I use .res and .fw file from here https://www.dropbox.com/s/bkbkndlv9tf3hol/fw00874.zip

**Comment by dpeddi** [comment]
Please consider that this tool is developed on linux os.
However I should have fixed this issue on latest commit. You may still get errors if you don't have imagemagick on your path

(convert should be imagemagick one and no the 
"C:\>convert /?
Converts a FAT volume to NTFS.")
